
# === Preprocess config ===

# --- Initial & Boundary and Forcing ---
grdname_src : /home/shjo/data/nifs02/sep_isl_test/roms_inputs/roms_grd_15km_subsampled.nc
grdname_dst : /home/shjo/data/nifs02/sep_isl_test/roms_inputs/roms_grd_fennel_5km_smooth_v3.nc

ininame_src : /home/shjo/applications/nifs02_5km/storage/nifs02_5km_aug_sep/trunk/nifs15km_ini.nc
ininame_dst : /home/shjo/applications/nifs02_5km/storage/nifs02_5km_aug_sep/trunk/nifs5km_ini.nc

weight_file: ./NWP_weight.nc
calc_weight: True

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True 

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

vertical_src:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400

vertical_dst:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400






