
# === Preprocess config ===

# --- Initial & Boundary and Forcing ---

grdname_src : /home/shjo/data/nifs02/aug_5km/roms_grd_fennel_5km_smooth_v3.nc
grdname_dst : /home/shjo/data/nifs02/aug_5km/roms_grd_15km_subsampled.nc

ininame_src : /home/shjo/applications/nifs02_5km_clm/storage/2025_jul/nifs02_5km_clm_rst.nc
ininame_dst : /home/shjo/data/nifs02/aug/roms_inputs/nifs15km_ini_250901_subsampled.nc

bio_model_type : npzd

weight_file: ./NWP_weight.nc
calc_weight: True

ncformat: NETCDF3_64BIT #NETCDF4 # NETCDF3_64BIT
force_write: True

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

vertical_src:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400

vertical_dst:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400















