
# === Preprocess config ===

# --- Initial & Boundary and Forcing ---

grdname_src : /home/shjo/data/nifs02/apr_may/roms_inputs/roms_grd_fennel_5km_topo_sync.nc
#grdname_dst : /home/shjo/data/nifs02/apr_may/roms_inputs/roms_grd_fennel_5km_topo_sync.nc
grdname_dst : /home/shjo/data/nifs02/sep_isl_test/roms_inputs/roms_grd_fennel_15km_smooth_v2.nc

ininame_src : /home/shjo/applications/nifs02_5km/storage/nifs02_isl_oct_re/nl/nifs5km_avg_9429_0008.nc
ininame_dst : /home/shjo/data/nifs02/nov/roms_inputs/nifs_rst_15km_20251101.nc

bio_model_type : npzd

weight_file: ./NWP_weight.nc
calc_weight: True

ncformat: NETCDF3_64BIT #NETCDF4 # NETCDF3_64BIT
force_write: True

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

vertical_src:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400

vertical_dst:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400















