
case               : leev2_tak_da8ol4_sst_kodc_surface
#case               : leev2_tak_da8ol4_ssh_sst_kodc
data_dir           : /home/shjo/applications/isl_system_v250925/storage/da8ol4_osita_kodc/nl/
data_prefix_header : wnp8km_avg_
base_dir           : /home/shjo/warehouse/nifs01/

grdname            : /home/shjo/applications/nifs01_spinup/storage/data/NWP12_grd_NWP4_topo_modi.nc


vars: ["zeta","u","v","temp", "salt", "chlorophyll", "NO3","phytoplankton"]


var_names:
  time_candidates: ["ocean_time", "time", "t"]
  lat_candidates: ["lat", "latitude", "y", "eta", "eta_rho"]
  lon_candidates: ["lon", "longitude", "x", "xi", "xi_rho"]
  z_candidates: ["s_rho", "z", "depth", "lev", "layer"]
  ref_time: "seconds since 2000-1-1"


