
case               : leev2_tak_clm
data_dir           : /home/shjo/applications/nifs01_spinup/storage/leev2_tak_clm/
data_prefix_header : leev2_tak_avg
base_dir           : /home/shjo/warehouse/nifs01/

grdname            : /home/shjo/applications/nifs01_spinup/storage/data/NWP12_grd_NWP4_topo_modi.nc


vars: ["temp", "salt", "chlorophyll", "NO3","phytoplankton"]


var_names:
  time_candidates: ["ocean_time", "time", "t"]
  lat_candidates: ["lat", "latitude", "y", "eta", "eta_rho"]
  lon_candidates: ["lon", "longitude", "x", "xi", "xi_rho"]
  z_candidates: ["s_rho", "z", "depth", "lev", "layer"]
  ref_time: "seconds since 2000-1-1"


